### ISSUE TITLE
TypeError: 'module' object is not callable

### ISSUE THREAD

**Issue by nguyenanhtuan1008** [hashemsellat/Video-Anomaly-Detection#11]
Traceback (most recent call last):
  File ".\Evaluation.py", line 32, in <module>
    evaluate()
  File ".\Evaluation.py", line 10, in evaluate
    dataProvider = DataProvider()
TypeError: 'module' object is not callable

I run python Evaluation.py and then got this error. Can someone help?

**Comment by Rangachary** [comment]
I'm also getting the same issue. can anyone help us in this?

**Comment by Rangachary** [comment]
Just changed the below lines
dataProvider = DataProvider()
images = dataProvider.get_testset(True)
to single line as,
images = DataProvider.get_testset(True)

it works for me....
